### ISSUE TITLE
Different Logo Per Course

### ISSUE THREAD

**Issue by UncleRaymondo** [learnweb/moodle-block_qrcode#22]
Hi,

Is it possible to have a different logo per course? Our Moodle Platform is multi-tenanted and we would like a different tenant logo for their respective courses.

Appreciate the assist.

Cheers,
Ray

**Comment by Dagefoerde** [comment]
Hi Ray, currently this is not possible. This would require additional code. In case you make changes to the plugin in order to achieve this, please create a pull request as we might consider it for integration.

**Comment by Laur0r** [comment]
Fixed by #37
