### ISSUE TITLE
QR Code Block Logo Not Working

### ISSUE THREAD

**Issue by GCappiello1** [learnweb/moodle-block_qrcode#32]
Hi,

I've recently installed the QR block (in Moodle version 3.9.7) but when the "Use logo" option is selected in the configure block screen, and a logo uploaded, the QR code fails to appear on screen.  The error message states that the logo is trying to pull from an invalid path, but I asked Moodle support to look into it and they couldn't find any issue with the logo's file path. They suggested it could be an issue with the block itself.  

Thanks.

**Comment by justusdieckmann** [comment]
Hi,

I can only reproduce the problem if I remove the uploaded logo file from the harddrive manually.
Have you tried deleting the logo in the filepicker and reuploading the same logo again?

If that does not work, could you try uploading another logo and could you post the entire error message?
Does this happen with the png or svg QR-Code (or both)?

Cheers
Justus

**Comment by GCappiello1** [comment]
Hi Justus,

I've tried reuploading the logo and loading several different logos, the problem still occurs. 
I can't seem to get any response from the block unless both a png and an svg logo have been added to the QR code settings. With only a png added either the standard Moodle logo, or no logo displays, depending on settings. With both added a broken link image appears. The whole error message is "Exception - Invalid logo path:" when the png format option is selected and "Exception - Call to a member function getAttribute() on null" when the svg is selected.

Many thanks.

**Comment by justusdieckmann** [comment]
Hey,

thank you for the information. I've looked over the code again, and found the function that is probably the culprit. It gets the path to the logo path in a very ... hacky way, and relies on some settings being the default value.

Do you by any chance have a nonstandard $CFG->filedir, or is something else about your filedir nondefault?

Could you try to either
- _if you use git_: checkout the `fix/filesystem-access` branch
- _otherwise_:  replace `<moodledir>/blocks/qrcode/classes/output_image.php` with this version https://raw.githubusercontent.com/learnweb/moodle-block_qrcode/fix/filesystem-access/classes/output_image.php

For me, the plugin now also works with a changed filedir. Does this also fix the problem for you?

Cheers
Justus

**Comment by GCappiello1** [comment]
Hi Justus,

Yes, the moodle filedir change has fixed the problem.

Many thanks.
