### ISSUE TITLE
Moodle logo is outdated

### ISSUE THREAD

**Issue by lucaboesch** [learnweb/moodle-block_qrcode#41]
Since 2018 (see https://commons.wikimedia.org/wiki/File:Moodle-logo.svg) the Moodle Logo is without "3D" mortarboard.
The logo should be adopted IMHO.

**Comment by justusdieckmann** [comment]
Hey @lucaboesch,

thank you for the message! Do you know where we could find a svg of the white `m` with black hat on orange background? It is used here as the icon for the moodle app https://support.moodle.com/support/solutions/80000457555

Thank you 
Justus

**Comment by lucaboesch** [comment]
I hope it is no problem if I send you the file I've taken somewhere.

![Moodle_M_icon](https://github.com/learnweb/moodle-block_qrcode/assets/377279/06434455-f453-46d4-85e4-eb3d309ea501)
