### ISSUE TITLE
Declare composer dependency

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-block_qrcode#5]
This is the least important, but should be done before (public) release:

Please write a `composer.json` that declares your dependency on QrCode.

**Comment by TamaraGunkel** [comment]
The `composer.json` already exists and is located under `thirdparty`.

**Comment by Dagefoerde** [comment]
Right, sorry. Thanks. The `composer.lock` elaborates on transitive dependencies. I think they should be declared explicitly in Moodle's `thirdpartylibs.xml` as well, and https://github.com/learnweb/moodle-block_qrcode/blob/e9c25baece0865b053f4219771b37b93cdb5c74b/thirdpartylibs.xml#L4 should point at `thirdparty/vendor/bacon/bacon-qr-code` instead.
